Document: stepmania
Title: Debian stepmania Manual
Author: <insert document author here>
Abstract: This manual describes what stepmania is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/stepmania/stepmania.sgml.gz

Format: postscript
Files: /usr/share/doc/stepmania/stepmania.ps.gz

Format: text
Files: /usr/share/doc/stepmania/stepmania.text.gz

Format: HTML
Index: /usr/share/doc/stepmania/html/index.html
Files: /usr/share/doc/stepmania/html/*.html
